---
- name: Get running configuration from Cisco switches and save output to log file
  hosts: cisco_devices
  gather_facts: no
  become: yes
  become_method: enable
  vars:
    ansible_become_pass: "cisco"
    total_score: 0
    aaa_auth_login_score: 0
    aaa_auth_exec_score: 0
  tasks:
    - name: Retrieve running configuration
      ios_command:
        commands:
          - show running-config
      register: run_config_output

    - name: Check for "aaa authentication login"
      set_fact:
        aaa_auth_login_score: "{{ 2 if 'aaa authentication login' in run_config_output.stdout[0] else 0 }}"
      when: "'aaa authentication login' in run_config_output.stdout[0]"
    
    - name: Check for "aaa authorization exec"
      set_fact:
        aaa_auth_exec_score: "{{ 1 if 'aaa authorization exec' in run_config_output.stdout[0] else 0 }}"
      when: "'aaa authorization exec' in run_config_output.stdout[0]"

    - name: Calculate total score
      set_fact:
        total_score: "{{ total_score + aaa_auth_login_score | int + aaa_auth_exec_score | int }}/20"

    - name: Save output to log file
      delegate_to: localhost
      block:
        - name: Save output to log file
          copy:
            content: |
              aaa authentication login: {{ aaa_auth_login_score }}
              aaa authorization exec: {{ aaa_auth_exec_score }}
              Total Score: {{ total_score }}
            dest: "{{ playbook_dir }}/output_{{ inventory_hostname }}.log"

