---
- name: Get running configuration from Cisco switches
  hosts: cisco_devices
  gather_facts: no  # We don't need to gather facts for this task
  become: yes
  become_method: enable
  vars:
    ansible_become_pass: "class"
  tasks:
    - name: Retrieve running configuration
      ios_command:
        commands:
          - show running-config
      register: run_config_output

    - name: Print running configuration
      debug:
        msg: "{{ run_config_output.stdout_lines }}"

#    - name: Check for "aaa authentication login"
#      debug:
#        msg: "Scored: {{ 1 if 'aaa authentication login' in run_config_output.stdout[0] else 0 }}"

#    - name: Check for "aaa authorization exec"
#      debug:
#        msg: "Scored: {{ 1 if 'aaa authorization exec' in run_config_output.stdout[0] else 0 }}"
