---
- name: Get running configuration from Cisco switches
  hosts: all_cisco_devices
  gather_facts: no  # We don't need to gather facts for this task
  become: yes
  become_method: enable

  vars:
    ansible_become_pass: class

  tasks:
    - name: Retrieve running configuration
      ios_command:
        commands:
          - show running-config | include ^username
      register: usernames_output

    - name: Extract usernames
      set_fact:
        usernames: "{{ usernames_output.stdout_lines | map('regex_replace', '^username (\\S+).*', '\\1') | list }}"

    - name: Display usernames
      debug:
        var: usernames

    - name: Configure privilege level 1 for all users
      ios_config:
        lines:
          - "username {{ item }} privilege 1"
        save_when: modified
      loop: "{{ usernames }}"
      notify: Save configuration

