---
- name: Get running configuration from Cisco switches
  hosts: all_cisco_devices
  gather_facts: no  # We don't need to gather facts for this task
  become: yes
  become_method: enable

  vars:
    ansible_become_pass: class

  tasks:
    - name: Retrieve running configuration
      ios_command:
        commands: show running-config
      register: running_config

    - name: Extract user accounts
      set_fact:
        user_accounts: "{{ running_config.stdout[0] | regex_findall('username \\S+.*') }}"

    - name: Check if users with privilege other than 1 exist
      set_fact:
        score: 0
      when: user_accounts | select('search', 'username \\S+ privilege \\d+') | list | length > 0

    - name: Set score to 1 if all users have privilege level 1
      set_fact:
        score: 1
      when: user_accounts | reject('search', 'username \\S+ privilege \\d+') | list | length == user_accounts | list | length

    - name: Display score
      debug:
        var: score
