---
- name: Get running configuration from Cisco switches
  hosts: all_cisco_devices
  gather_facts: no  # We don't need to gather facts for this task
  become: yes
  become_method: enable

  roles:
    - role: /root/cis_benchmark/configuration_role

  vars:
    ansible_become_pass: class

  pre_tasks:
    - name: Set up RADIUS and TACACS+ servers
      include_tasks: /root/cis_benchmark/configuration_role/tasks/configure_radius_and_tacacs_playbook.yml

  tasks:
    - name: AAA Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/local_AAA.yml

    - name: Access Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/access_rules_playbook.yml

    - name: Banner Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/banner_rules_playbook.yml

    - name: Password Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/password_rules_playbook.yml

    - name: SNMP Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/snmp_rules_playbook.yml

    - name: Global Service Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/global_service_rules_playbook.yml

    - name: Logging rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/logging_rules_playbook.yml

    - name: NTP rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/ntp_rules_playbook.yml

    - name: Loopback rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/loopback_rules_playbook.yml

    - name: Routing rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/routing_rules_playbook.yml

    - name: Task for border router R3 only
      include_tasks: /root/cis_benchmark/configuration_role/tasks/border_router_filtering_playbook.yml
      when: inventory_hostname == 'R3'

    - name: Neighbor Authentication Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/neighbor_authentication_playbook.yml

    - name: OSPF Authentication Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/require_ospf_authentication_if_protocol_is_used_playbook.yml

    - name: RIPv2 Authentication Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/require_ripv2_authentication_if_protocol_is_used_playbook.yml

    - name: BGP Authentication Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/bgp_playbook.yml
