---
# Pre Task 1
- name: Configure enable secret [1 Point]
  cisco.ios.ios_config:
    lines:
      - "enable secret {{enable_secret}}"

# Pre Task 2
- name: Configure backup user
  cisco.ios.ios_config:
    lines:
      - username nyaoga privilege 1 password oh

- name: Enable 'aaa new-model'Enable 'aaa new-model' [1 point]
  cisco.ios.ios_config:
    lines:
      - aaa new-model

# Pre Task 3
- name: Configure RADIUS server
  cisco.ios.ios_config:
    lines:
      - "radius server {{ aaa_radius_config.server_name }}"
      - " address ipv4 {{ aaa_radius_config.server_ip }} auth-port 1812 acct-port 1813"
      - " key {{ aaa_radius_config.key }}"

#Pre Task 4
- name: Configure AAA group server radius
  cisco.ios.ios_config:
    lines:
      - "aaa group server radius {{ aaa_radius_config.group_name }}"
      - " server name {{ aaa_radius_config.server_name }}"

# Pre Task 5
- name: Configure TACACS server
  cisco.ios.ios_config:
    lines:
      - "tacacs server {{ aaa_tacacs_config.server_name }}"
      - " address ipv4 {{ aaa_tacacs_config.server_ip }} "
      - " key {{ aaa_tacacs_config.key }}"

#Pre Task 6
- name: Configure AAA group server TACACS
  cisco.ios.ios_config:
    lines:
      - "aaa group server tacacs+ {{ aaa_tacacs_config.group_name }}"
      - " server name {{ aaa_tacacs_config.server_name }}"

- name: 1.1.2 Enable 'aaa authentication login' [4 point]
  cisco.ios.ios_config:
    lines:
      - >
        aaa authentication login
        {{ aaa_authentication_login.list_name }}
        {{ aaa_authentication_login.group }}
        {{ aaa_authentication_login.method1 }}
        {{ aaa_authentication_login.method2 }}

- name: 1.1.3 Enable 'aaa authentication enable default' [1 point]
  cisco.ios.ios_config:
    lines:
      - >
        aaa authentication enable
        {{ aaa_authentication_enable.list_name }}
        {{ aaa_authentication_enable.method1 }}
        {{ aaa_authentication_enable.group }}
        {{ aaa_authentication_enable.method2 }}

- name: 1.1.7 - 1.1.11 Configure AAA accounting commands (commands 15, connection, exec, network, system) [5 points] 
  cisco.ios.ios_config:
    lines: >
      aaa accounting {{ item }}
      {{ aaa_accounting_config.list_name }}
      {{ aaa_accounting_config.method }}
      {{ aaa_accounting_config.server_type }}
      {{ aaa_accounting_config.tacacs_server_group_name }}
  loop: "{{ aaa_accounting_config.accounting_types }}"


# Pre Task 7
- name: Configure line vty
  cisco.ios.ios_config:
    lines:
      - "line vty 0 15"
      - "transport input all"

