---
#1.3
- name: 1.3.1 - 1.3.1 Set the banner text for exec, login, and MOTD [3 Points]
  cisco.ios.ios_banner:
    banner: "{{ item }}"
    text: "Welcome to {{ inventory_hostname }} {{ item | upper }} banner."
    state: present
  loop:
    - exec
    - login
    - motd

