---
- name: Configure BGP neighbor remote-as
  cisco.ios.ios_config:
    lines:
      - "neighbor {{ item.ip }} remote-as {{item.remote_as_number}}"
    parents: "router bgp {{item.bgp_as_number}}"
  with_items: "{{ bgp_neighbors }}"
  register: bgp_remote_as_config

- name: Configure BGP neighbor authentication
  cisco.ios.ios_config:
    lines:
      - neighbor {{ item.ip }} password {{item.password }}
    parents: router bgp {{ item.bgp_as_number }}
  with_items: "{{ bgp_neighbors }}"
  register: bgp_config_output

- name: Debug BGP configuration output
  debug:
    var: bgp_config_output

