---
- name: Configure BGP neighbor remote-as
  cisco.ios.ios_config:
    lines:
      - "neighbor {{item.peer_group_name}} peer-group"
      - "neighbor {{item.peer_group_name}} remote-as {{item.remote_as_number}}"
      - "neighbor {{ item.neighbor_ip }} peer-group {{item.peer_group_name}}"
    parents: "router bgp {{item.bgp_as_number}}"
  with_items: "{{ bgp_neighbors }}"
  register: bgp_remote_as_config

- name: Configure BGP neighbor authentication
  cisco.ios.ios_config:
    lines:
      - neighbor {{ item.neighbor_ip }} password {{item.password }}
    parents: router bgp {{ item.bgp_as_number }}
  with_items: "{{ bgp_neighbors }}"
  register: bgp_config_output

