---
#/root/cis_benchmark/config_role/tasks/local_AAA
#Local Authentication, Authorization and Accounting (AAA) Rules
- name: 1.1.1 Enable 'aaa new-model' [1 point]
  cisco.ios.ios_config:
    lines:
      - aaa new-model

- name: 1.1.2 Enable 'aaa authentication login' [1 point]
  cisco.ios.ios_config:
    lines:
      - >
        aaa authentication login
        {{ aaa_authentication_login.list_name }}
        {{ aaa_authentication_login.group }}
        {{ aaa_authentication_login.method1 }}
        {{ aaa_authentication_login.method2 }}

- name: 1.1.3 Enable 'aaa authentication enable default' [1 point]
  cisco.ios.ios_config:
    lines:
      - >
        aaa authentication enable
        {{ aaa_authentication_enable.list_name }}
        {{ aaa_authentication_enable.method1 }}
        {{ aaa_authentication_enable.group }}
        {{ aaa_authentication_enable.method2 }}

- name: 1.1.4 and 1.1.6 Set 'login authentication for 'line con 0 and line vty 0 15' [2 points]
  cisco.ios.ios_config:
    lines: 
      - line {{ item }}
      - login authentication {{ aaa_authentication_login.list_name }}
  loop: "{{ line_types }}"


- name: 1.1.7 - 1.1.11 Configure AAA accounting commands (commands 15, connection, exec, network, system) [5 points] 
  cisco.ios.ios_config:
    lines: >
      aaa accounting {{ item }}
      {{ aaa_accounting_config.list_name }}
      {{ aaa_accounting_config.method }}
      {{ aaa_accounting_config.server_type }}
      {{ aaa_accounting_config.tacacs_server_group_name }}
  loop: "{{ aaa_accounting_config.accounting_types }}"
