---
- name: 2.3.1.1 Set 'ntp authenticate'
  cisco.ios.ios_config:
    lines:
      - ntp authenticate

- name: 2.3.1.2 Set 'ntp authentication-key' 
  cisco.ios.ios_config:
    lines:
      - ntp authentication-key {{ ntp_key_id }} md5 {{ ntp_key_hash }}

- name: 2.3.1.3 Set the 'ntp trusted-key'
  cisco.ios.ios_config:
    lines:
      - ntp trusted-key {{ntp_key_id}}

- name: 2.3.2 Set 'key' for each 'ntp server'
  cisco.ios.ios_config:
    lines:
      - "ntp server {{ item }} key {{ ntp_key_id }}"
  loop: "{{ ntp_servers }}"

