#1.4
- name: 1.4.1 Set 'password' for 'enable secret' [1 Point]
  cisco.ios.ios_config:
    lines:
      - enable secret {{enable_secret}}

- name: 1.4.2 Enable 'service password-encryption' [1 Point]
  cisco.ios.ios_config:
    lines: "service password-encryption"

- name: 1.4.3 Set 'username secret' for all local users [1 Point]
  cisco.ios.ios_config:
    lines: "username {{ item.username }} secret {{ item.password }}"
  loop: "{{ local_users }}"
  no_log: true
