--- 
- name: Register output of 'show running-config | include aaa new-model'
  cisco.ios.ios_command:
    commands:
      - show running-config | include aaa new-model
  register: aaa_new_model_output

- name: Score '1.1.1 Enable aaa new-model' 
  set_fact:
    aaa_new_model_score: >-
      {{
        0 if aaa_new_model_output.stdout[0] == '' or 'no aaa new-model' in aaa_new_model_output.stdout[0] 
        else 1
      }}

- name: Register output of 'show running-config | include aaa authentication login'
  cisco.ios.ios_command:
    commands:
      - show running-config | include aaa authentication login
  register: aaa_auth_output

- name: Score 1.1.2 Enable 'aaa authentication login' 
  set_fact:
    aaa_auth_login_score: "{{ 1 if aaa_auth_output.stdout_lines != [['']] else 0 }}"

- name: Register output of 'show running-config | include aaa authentication enable'
  cisco.ios.ios_command:
    commands:
      - show running-config | include aaa authentication enable
  register: aaa_auth_output

- name: Score 1.1.3 Enable 'aaa authentication enable default'  
  set_fact:
    aaa_auth_enable_score: "{{ 1 if aaa_auth_output.stdout_lines != [['']] else 0 }}"

- name: Register output of 'sh run | sec line | incl login authentication'
  cisco.ios.ios_command:
    commands:
      - sh run | sec line | incl login authentication
  register: login_auth_output

- name: Score 1.1.4 Set 'login authentication for 'line con 0' 
  set_fact:
    aaa_login_auth_line_con_0: >-
      {{
        1 if 'line con 0' in login_auth_output.stdout[0]
        else 0
      }}

- name: 1.1.6 Set 'login authentication for 'line vty' 
  set_fact:
    aaa_login_auth_line_vty: >-
      {{
        1 if 'line vty 0 4' in login_auth_output.stdout[0]
        else 0
      }}
    
- name: Register output of 'show run | include aaa accounting commands'
  cisco.ios.ios_command:
    commands:
      - show run | include aaa accounting commands
  register: aaa_accounting_commands_output

- name: Score 1.1.7 Set 'aaa accounting' to log all privileged use commands using 'commands 15'
  set_fact:
    aaa_accounting_commands_score: "{{ 1 if aaa_accounting_commands_output.stdout[0] != '' else 0 }}"

- name: Register output of 'show run | include aaa accounting connection'
  cisco.ios.ios_command:
    commands:
      - show run | include aaa accounting connection
  register: aaa_accounting_connection_output

- name: Score 1.1.8 Set 'aaa accounting connection'
  set_fact:
    aaa_accounting_connection_score: "{{ 1 if aaa_accounting_connection_output.stdout[0] != '' else 0 }}"

- name: Register output of 'show run | include aaa accounting exec'
  cisco.ios.ios_command:
    commands:
      - show run | include aaa accounting exec
  register: aaa_accounting_exec_output

- name: Score 1.1.9 Set 'aaa accounting exec'
  set_fact:
    aaa_accounting_exec_score: "{{ 1 if aaa_accounting_exec_output.stdout[0] != '' else 0 }}"

- name: Register output of 'show run | include aaa accounting network'
  cisco.ios.ios_command:
    commands:
      - show run | include aaa accounting network
  register: aaa_accounting_network_output

- name: Score 1.1.10 Set 'aaa accounting network'
  set_fact:
    aaa_accounting_network_score: "{{ 1 if aaa_accounting_network_output.stdout[0] != '' else 0 }}"

- name: Register output of 'show run | include aaa accounting system'
  cisco.ios.ios_command:
    commands:
      - show run | include aaa accounting system
  register: aaa_accounting_system_output

- name: Score 1.1.11 Set 'aaa accounting system'
  set_fact:
    aaa_accounting_system_score: "{{ 1 if aaa_accounting_system_output.stdout[0] != '' else 0 }}"
